- hosts: localhost
  vars_files:
    - mysecret.yml
  tasks:
  - name: Sending mail from ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ uname }}"
      password: "{{ pass }}"
      to: iamragh@gmail.com 
      subject: Ansible-report
      body: Mail Send From Ansible.

