#This playbook will show you how to use template module for dynamic content in text file
- hosts: all
  vars:
    - myname: "Raghav"
  tasks:
   - name: Copy the files using template module
     template:
       src: test.txt.j2 
       dest: /myindex.txt 
